### ISSUE TITLE
Version checking and database upgrade scripts.

### ISSUE THREAD

**Issue by bsefton12** [DPIclimate/broker#35]
We need upgrade scripts to apply database upgrades automatically.
This also requires some form of version number which we can tie the upgrade scripts to.  Enabling the system to sequentially apply the upgrade scripts.

**Comment by dajtxx** [comment]
Fixed with commits e4b75444bc290ec979956083488a250c2f57ee2e, 1caf7d4dc24182dd4ae0ecebae2bc11900af5c68
