### ISSUE TITLE
Add last parameter to the physical_timeseries REST API endpoint

### ISSUE THREAD

**Issue by dajtxx** [DPIclimate/broker#46]
The start and end are not very friendly for charting, it would be nice to be able to say last=nx where

* n is an integer
* x is `h` hours, `d` days, `m` months, `y` years

So `last=3h` returns any messages from the last 3 hours, etc.

Perhaps a limit=n would be good too where `n` means the most recent `n` messages.

**Comment by kebab01** [comment]
I see that this issue was fixed on the 14th July with commit id: 787532deb0056525206fdabd9616911b44045e10
